### ISSUE TITLE
Avatar Command Not Working

### ISSUE THREAD

**Issue by ghost** [littlestudios69/Pika#11]
Pikas p*avatar command is unresponsive. 
![a83070f737c430aa21eecbd702fead15](https://user-images.githubusercontent.com/83475317/116838026-e168ff00-ab9a-11eb-911e-a1d353bd3568.png)

**Comment by ImFelixprogram** [comment]
Hi @VerifiedProxy ,
oof, the code includes wrong variable names and copy&paste-errors. InfoBlock should really check his code before he pushes.
Will be fixed within the next commit.

~ Felixprogram, CTO of Little Studios
