### ISSUE TITLE
Feature: Call

### ISSUE THREAD

**Issue by rexjohannes** [littlestudios69/Pika#14]
Please add a Call function that allows to set a call channel and call another server by id to create a chat between two server.
To start a call use one command and then in the channel of the other server a message will get posted that there is an ongoing call with accept and reject (reactions or command). If accepted all messages from both channels will transferred (using webhook or bot message) To end call just add an end command.

**Comment by VerifiedProxy** [comment]
@rexjohannes I think what you're referring to is the same feature (Yggdrasil) has. We have something like that already that allows users to communicate globally. I don't see the need for this feature in my opinion. I'm gonna have to downvote this one. 👎

**Comment by rexjohannes** [comment]
Yes there is an GlobalChat but thats is between all little pika servers

**Comment by VerifiedProxy** [comment]
Makes sense. I was unaware of the feature you were mentioning. I had to do some research my self. Seems like a nice feature. Thanks for the suggestion. Hopefully, the devs take this into consideration. Change my vote to 👍.

**Comment by taynotfound** [comment]
Hi Johannes,

That's an good idea tbh.


We will look into it and maybe implement it!



Tayron
