### ISSUE TITLE
Feature: Clear Command

### ISSUE THREAD

**Issue by rexjohannes** [littlestudios69/Pika#17]
Please add an Clear/Purge Command to Little Pika

**Comment by ImFelixprogram** [comment]
Hi @rexjohannes ,

we will add that, but keep in mind that [discord's limit](https://discord.com/developers/docs/resources/channel#bulk-delete-messages) as far as "purging" channels is 100 messages / not older than 2 weeks.
Yes, this _is_ bypassible but it would require to delete messages "manually" one by one which would likely lead wither to bad performance or a rate limit, which means, we won't allow purging more than that limit.

~ Felixprogram, CTO of Little Studios
