### ISSUE TITLE
Feature: Invite Counter

### ISSUE THREAD

**Issue by rexjohannes** [littlestudios69/Pika#19]
Please add an Invite Counter to little Pika thats counts the invites from a user and optionaly displays how invited him in join message

**Comment by ImFelixprogram** [comment]
Hi @rexjohannes ,

as far as I know, it's not possible that we can get through which invite link a user joined, only the member itself is passed by discord.js as you can see in its' [source](https://github.com/discordjs/discord.js/blob/master/src/client/websocket/handlers/GUILD_MEMBER_ADD.js) .
If it really **is** possible somehow, please help us out with a solution.
_This will be closed for now._

~ Felixprogram, CTO of Little Studios
