### ISSUE TITLE
Bug: AutoRole not Working

### ISSUE THREAD

**Issue by rexjohannes** [littlestudios69/Pika#22]
AutoRole Setuped in Pika https://rexum.likes.cash/kp3z59n719a but on join the Role is not given and the but has Admin and has and higher role then the autorole

**Comment by ImFelixprogram** [comment]
Hi @rexjohannes ,

I'll try to reproduce that bug.
Could you please also upload a screenshot of your role hierarchy and the page with the bot's permissions on your server?

~ Felixprogram, CTO of Little Studios

**Comment by rexjohannes** [comment]
https://rexum.hates-you.xyz/kpoebc5449a
https://rexum.likes.cash/kpoebyao49a
